batch_size: 512
epochs: 500
lr: 0.00001
log_neptune: True
negative_sample_ratio: 8

in_channels: 1280
model_type: rinalmo
gnn_channels:
  - 1280
  - 512
  - 512
  - 256
cnn_channels:
  - 1280
  - 1280
  - 1280
  - 64
dropout: 0.3
