batch_size: 256
epochs: 500
lr: 0.001
log_neptune: True
negative_sample_ratio: 4

in_channels: 4
model_type: global
gnn_channels:
  - 128
  - 256
  - 128
  - 64
cnn_channels:
  - 128
  - 256
  - 128
  - 64
dropout: 0.2
