# Training
log_neptune: True

batch_size: 512
epochs: 500
lr: 0.00001
min_lr: 0.00000001

# Negative Sampling
negative_sample_ratio: 8
hard_negative_sampling: True

# Gradient Clipping
use_gradient_clipping: False
gradient_clip_value: 0.5
gradient_clip_algorithm: value

# Scheduler
use_scheduler: True
scheduler_patience: 10

# Architecture
model_type: rinalmo
freeze_embeddings: False
in_channels: 1280
gnn_channels:
  - 512
  - 256
  - 256
  - 128
out_channels: 128
cnn_head_embed_dim: 64
cnn_head_num_blocks: 2
dropout: 0.2
